#!/bin/bash
idenaURL=$(curl -s 'https://github.com/idena-network/idena-go/releases/' |grep idena-node-linux | cut -d '"' -f 2 | cut -d '-' -f 6 | head -n 1)
idenaTXT=$(idena -v | awk '{print $3}')
if [[ ! $idenaURL == $idenaTXT ]];then
	service idena stop
    systemctl stop idena.target
		if [ -d /home/datadir/idenachain.db ]
		then
		wget https://media.githubusercontent.com/media/znyber/idena-installer/master/idenachain.db.zip -O /home/datadir/
		rm -rf /home/datadir/idenachain.db
		unzip /home/datadir/idenachain.db.zip -d /home/datadir/
		else
		echo "directory tidak ada"
		fi
    wget https://github.com/idena-network/idena-go/releases/download/v$idenaURL/idena-node-linux-$idenaURL -q --show-progress -O /usr/bin/idena
    chmod +x /usr/bin/idena
	service idena start
    systemctl start idena.target
    wall idena update version $idenaURL
    exit 0
    else
        echo -e "version $idenaURL no Update"
        exit 1
    fi